title:            Christopher T. Ogden
description:      My personal blog
url:              http://ctogden.com/archives/
signoff:          Christopher T. Ogden
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-28419049-1

links:
  - name:         Blog
    url:          /archives
  - name:         About
    url:          /about
  - name:         Projects
    url:          /projects
highlighter:      pygments
permalink:        pretty
markdown: 	      kramdown
